#include <iostream>
#include <cstdlib>
#include "Scheduler.h"

using namespace std;

void Scheduler::Select_Schedule()
{
	int Choice;
	while(1)
	{
		cout<<"\nEnter mode of scheduling the available processes \n1.	First Come First Serve scheduling\n2.	Shortest Job First scheduling \n3.	Shortest Remaining Time Next scheduling\n4.	Round Robin scheduling\n5.	Static Priority scheduling\n6.	Dynamic Priority scheduling\n7.	Highest Response Ratio Next\n0.	Exit :\n";
		cin>>Choice;
		switch(Choice)
		{
			case 1:	First_Come_First_Serve();
					Sort_By(Arrival_Time);
					break;
			case 2:	Shortest_Job_First();
					Sort_By(Service_Time);
					break;
			case 3:	Shortest_Remaining_Time_Next();
					break;
			case 4:	Round_Robin();
					Sort_By(Process_ID);
					break;
			case 5:	Static_Priority();
					break;
			case 6: Dynamic_Priority();
					break;
			case 7: Highest_Response_Ratio_Next();
					break;
			case 0:	exit(0);
			default:cout<<"\n\t\tInvalid choice!!! Retry\n";
					continue;
		}
		Formatted_Output();
		Sort_By(Process_ID);
	}
}

int main()
{
	//Object Creation and Process Details Input
	Scheduler s;
	int Choice;
	while(1)
	{
		cout<<"\nEnter the choice for input mode:\n1.	Manual Input\n2.	AutoGenerated Input\n3.	Files as Processes\n==>	";
		cin>>Choice;
		switch(Choice)
		{
			case 1:	s.Manual_Input();
					break;
			case 2:	s.AutoGen_Input();
					break;
			case 3:	s.Files_As_Processes();
					break;
			default:cout<<"\n\t\tInvalid choice for input mode!!! Retry\n";
					continue;
		}
		break;
	}
	s.Select_Schedule();
	return 0;
}